const MAX_NOTIFICATIONS = 1000;
const MAX_HISTORY = 1000;
const DEFAULT_TIME_TO_ANSWER = 10;  // seconds
const MAX_DRAFTS = 10;

module.exports = { MAX_NOTIFICATIONS, MAX_HISTORY, DEFAULT_TIME_TO_ANSWER, MAX_DRAFTS };
